# Generated by Django 3.1 on 2025-06-06 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
        ('sociosCuota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socioscuota',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socio', verbose_name='id'),
        ),
    ]
